const VARIANTS={family:{label:'Family',accent:'#6f4ea1',prompt:'What’s happening right now?',actions:[['feed','Feed','timer'],['sleep','Sleep','timer'],['nappy','Nappy change','stamp'],['medicine','Medicine','stamp'],['play','Play','timer'],['outside','Outside','timer']]},enterprise:{label:'Enterprise',accent:'#5d477a',prompt:'What are you working on?',actions:[['start','Start work','stamp'],['project','Project / Job','timer'],['meeting','Meeting','timer'],['support','Support','timer'],['admin','Administration','timer'],['training','Training','timer'],['break','Break','timer'],['finish','Finish work','stamp']]},sport:{label:'Sport',accent:'#35665a',prompt:'What are you doing in this session?',actions:[['warmup','Warm-up','timer'],['drill','Drill','timer'],['strength','Strength','timer'],['conditioning','Conditioning','timer'],['game','Match / Event','timer'],['recovery','Recovery','timer'],['hydration','Hydration','stamp'],['note','Session note','stamp']]}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let variant=localStorage.getItem('timestem.variant')||'enterprise',view='today';
function key(){return `timestem.${variant}`}
function actionKey(){return `timestem.${variant}.actions`}
function load(){try{let s=JSON.parse(localStorage.getItem(key()))||{entries:[],activeTimers:[]};if(s.active&&!s.activeTimers){s.activeTimers=[s.active];delete s.active}if(!Array.isArray(s.activeTimers))s.activeTimers=[];return s}catch{return{entries:[],activeTimers:[]}}}
function save(s){localStorage.setItem(key(),JSON.stringify(s))}
function defaultActions(){return VARIANTS[variant].actions.map(a=>[...a])}
function loadActions(){try{return JSON.parse(localStorage.getItem(actionKey()))||defaultActions()}catch{return defaultActions()}}
function saveActions(actions){localStorage.setItem(actionKey(),JSON.stringify(actions))}
function now(){return Date.now()}
function fmtTime(v){return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(v)}
function fmtDate(v){return new Intl.DateTimeFormat(undefined,{weekday:'short',day:'numeric',month:'short'}).format(v)}
function duration(ms){let m=Math.max(0,Math.round(ms/60000));return m<60?`${m} min`:`${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`}
function sameDay(a,b){let x=new Date(a),y=new Date(b);return x.toDateString()===y.toDateString()}
function startWeek(v=now()){let d=new Date(v),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);d.setHours(0,0,0,0);return d.getTime()}
function finishTimer(s,actionId,end=now()){let i=s.activeTimers.findIndex(x=>x.actionId===actionId);if(i<0)return null;let active=s.activeTimers[i],e={id:crypto.randomUUID(),actionId:active.actionId,label:active.label,mode:'timer',started:active.started,ended:end};s.entries.unshift(e);s.activeTimers.splice(i,1);return e}
function tap(action){let s=load(),t=now(),[id,label,mode]=action;if(mode==='stamp'){s.entries.unshift({id:crypto.randomUUID(),actionId:id,label,mode,started:t,ended:t})}else{let existing=s.activeTimers.find(x=>x.actionId===id);if(existing)finishTimer(s,id,t);else s.activeTimers.push({actionId:id,label,started:t})}save(s);render()}
function removeEntry(id){let s=load();s.entries=s.entries.filter(e=>e.id!==id);save(s);render()}
function setVariant(v){variant=v;localStorage.setItem('timestem.variant',v);document.documentElement.style.setProperty('--accent',VARIANTS[v].accent);render()}
function card(title,body=''){return `<section class="card"><div class="stack"><strong>${title}</strong>${body}</div></section>`}
function renderToday(main){let cfg=VARIANTS[variant],s=load(),actions=loadActions(),tpl=$('#today-template').content.cloneNode(true);main.appendChild(tpl);$('#variant-label').textContent=`TIMESTEM ${cfg.label.toUpperCase()}`;let h=new Date().getHours();$('#greeting').textContent=h<12?'Good morning':h<17?'Good afternoon':'Good evening';$('#prompt').textContent=cfg.prompt;if(s.activeTimers.length){$('#active-wrap').innerHTML=`<section class="active-list">${s.activeTimers.map(a=>`<section class="card active-card"><div class="active-row"><div class="stack"><span class="eyebrow">RUNNING</span><strong>${a.label}</strong><span class="muted">Started ${fmtTime(a.started)}</span></div><button class="primary finish-timer" data-id="${a.actionId}">Finish</button></div></section>`).join('')}</section>`;$$('.finish-timer').forEach(b=>b.onclick=()=>{let x=load();finishTimer(x,b.dataset.id);save(x);render()})}let grid=$('#action-grid');actions.forEach(a=>{let running=s.activeTimers.some(x=>x.actionId===a[0]),b=document.createElement('button');b.className='action-btn'+(running?' running':'');b.innerHTML=`<span class="dot">${a[2]==='timer'?'◷':'+'}</span><strong>${a[1]}</strong><span>${a[2]==='timer'?(running?'Tap to stop':'Tap to start'):'Tap to record'}</span>`;b.onclick=()=>tap(a);grid.appendChild(b)});let latest=s.entries.filter(e=>sameDay(e.started,now())).slice(0,3);$('#latest-wrap').innerHTML=latest.length?`<section><div class="section-head"><span>LATEST TODAY</span></div><div class="card log-list">${latest.map(e=>`<div class="log-row"><div><strong>${e.label}</strong><div class="muted">${fmtTime(e.started)}</div></div><strong>${e.ended>e.started?duration(e.ended-e.started):''}</strong></div>`).join('')}</div></section>`:''}
function renderLog(main){let s=load();main.innerHTML=`<section class="hero-card"><div class="eyebrow">${VARIANTS[variant].label.toUpperCase()} LOG</div><h2>Your timeline</h2><p>Correct mistakes instead of reconstructing the day later.</p></section>`;let entries=s.entries;if(!entries.length){main.insertAdjacentHTML('beforeend',card('Nothing logged yet','<span class="muted">Your taps and timers will appear here.</span>'));return}let wrap=document.createElement('section');wrap.className='card log-list';entries.forEach(e=>{let row=document.createElement('div');row.className='log-row';row.innerHTML=`<div><strong>${e.label}</strong><div class="muted">${fmtDate(e.started)} · ${fmtTime(e.started)}</div></div><div class="stack" style="text-align:right"><strong>${e.ended>e.started?duration(e.ended-e.started):''}</strong><button class="secondary danger">Delete</button></div>`;row.querySelector('button').onclick=()=>removeEntry(e.id);wrap.appendChild(row)});main.appendChild(wrap)}
function renderSummary(main){let s=load(),start=startWeek(),end=start+7*86400000,entries=s.entries.filter(e=>e.started>=start&&e.started<end),totals={};entries.filter(e=>e.ended>e.started).forEach(e=>totals[e.label]=(totals[e.label]||0)+(e.ended-e.started));let total=Object.values(totals).reduce((a,b)=>a+b,0);main.innerHTML=`<section class="hero-card"><div class="eyebrow">THIS WEEK · ${VARIANTS[variant].label.toUpperCase()}</div><h2>${duration(total)} tracked</h2><p>${summaryCopy()}</p></section><section class="card summary-list">${Object.keys(totals).length?Object.entries(totals).map(([n,v])=>`<div class="summary-row"><span>${n}</span><strong>${duration(v)}</strong></div>`).join(''):'<span class="muted">No timed activity recorded this week.</span>'}</section><button class="primary" id="copy-summary">Copy weekly summary</button>`;$('#copy-summary').onclick=async()=>{let lines=[`TimeStem ${VARIANTS[variant].label} — Weekly Summary`,...Object.entries(totals).map(([n,v])=>`${n}: ${duration(v)}`),`Total tracked: ${duration(total)}`];await navigator.clipboard.writeText(lines.join('\n'));$('#copy-summary').textContent='Copied'} }
function summaryCopy(){if(variant==='enterprise')return 'A work log assembled from the moments you already captured.';if(variant==='family')return 'See where the week went without rebuilding it from memory.';return 'A simple picture of training time across the week.'}
function renderSettings(main){let actions=loadActions();main.innerHTML=`<section class="hero-card"><div class="eyebrow">SETTINGS</div><h2>TimeStem ${VARIANTS[variant].label}</h2><p>Make the quick-tap screen fit how you actually use it.</p></section><section class="card settings-grid"><div><strong>Customise buttons</strong><p class="muted">Rename buttons and choose whether each one records a timestamp or runs as an independent timer.</p></div><div id="action-editor" class="action-editor"></div><div class="settings-actions"><button class="secondary" id="add-action">+ Add button</button><button class="secondary" id="reset-actions">Restore defaults</button></div><div class="notice">This web prototype stores this variant’s history and button layout only in this browser.</div><button class="secondary danger" id="clear-data">Clear ${VARIANTS[variant].label} data</button></section>`;let editor=$('#action-editor');function draw(){editor.innerHTML='';actions.forEach((a,i)=>{let row=document.createElement('div');row.className='edit-row';row.innerHTML=`<input class="action-name" value="${a[1].replace(/"/g,'&quot;')}" aria-label="Button name"><div class="mode-toggle" role="group" aria-label="Button type"><button type="button" class="mode-pill ${a[2]==='timer'?'active':''}" data-mode="timer">Timer</button><button type="button" class="mode-pill ${a[2]==='stamp'?'active':''}" data-mode="stamp">Timestamp</button></div><button class="icon-action remove-action" aria-label="Remove ${a[1]}" title="Remove button">×</button>`;let input=row.querySelector('input');input.onchange=()=>{actions[i][1]=input.value.trim()||'Untitled';saveActions(actions)};row.querySelectorAll('.mode-pill').forEach(btn=>btn.onclick=()=>{actions[i][2]=btn.dataset.mode;saveActions(actions);draw()});row.querySelector('.remove-action').onclick=()=>{actions.splice(i,1);saveActions(actions);draw()};editor.appendChild(row)})}draw();$('#add-action').onclick=()=>{actions.push([`custom-${crypto.randomUUID()}`,'New activity','stamp']);saveActions(actions);draw();setTimeout(()=>editor.lastElementChild?.querySelector('input')?.focus(),0)};$('#reset-actions').onclick=()=>{actions=defaultActions();saveActions(actions);draw()};$('#clear-data').onclick=()=>{if(confirm(`Clear all ${VARIANTS[variant].label} browser data?`)){localStorage.removeItem(key());render()}}}
function render(){document.documentElement.style.setProperty('--accent',VARIANTS[variant].accent);$$('.variant-switcher button').forEach(b=>b.classList.toggle('active',b.dataset.variant===variant));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#page-title').textContent=variant==='enterprise'?'Every tap builds your workday.':'Every tap builds your day.';let main=$('#main');main.innerHTML='';({today:renderToday,log:renderLog,summary:renderSummary,settings:renderSettings}[view])(main)}
$$('.variant-switcher button').forEach(b=>b.onclick=()=>setVariant(b.dataset.variant));$$('.bottom-nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('#theme-toggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('timestem.dark',document.body.classList.contains('dark')?'1':'0')};if(localStorage.getItem('timestem.dark')==='1')document.body.classList.add('dark');if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();